### ISSUE TITLE
卡在准备前往阅读器获取URL...

### ISSUE THREAD

**Issue by hifuclub** [cpuopt/DLsite-Play-Downloader#1]
卡在准备前往阅读器获取URL...
阅读器的网页正常弹出，但是之前页面的日志卡在准备前往阅读器获取URL...

**Comment by cpuopt** [comment]
可以给一下作品链接吗，我这边试了一下是没问题的

**Comment by hifuclub** [comment]
https://www.dlsite.com/books/work/=/product_id/BJ01294074

https://play.dlsite.com/csr/viewer/vertical?cgi=https%3A%2F%2Fplay.dl.dlsite.com%2Fcsr%2Fapi%2Fdiazepam_hybrid.php&customer_id=SFT000001335395&margin=0&param=quV%2BMsl915%2FzT58VqvfOZx7ZbMv7U68l93NUxeIcqxdby%2BUO9T%2FKF335tuyE4wrqQlSFMGHt%2FcLdn3eSVLvEp8%2BnHxOei3eoEvdEndGb54pZEfDx3fgQ6w93vznM5goPJaN25R0Bm4dzDJUbyNron04aLxGvpmD6RYVV3kmCZDFmQrfCp9FLtVQTBqbODHqlQCrYqHSojAjqmuxpsl%2Bw5xm7kElELd30ldUEIMxTCB%2BnO4iSr%2FrcBEoXCwJ5GWOjx4eE6ogtNaQvb6fdppS4DH47c645r6sNK2r4BM1HfRodVxkHTnVSbylYHryxWyZkbB5ZgmtpiE84hATxzPPs%2B38YVX9seAMiyNn6InEHTXvPRz%2FzmzI4BZlZQQMgnr5MNJhMzUc08nTIU9ikhvCprsh3ceBkjxsUjYOkITSX7wJ4nRVfBDlcPxBTHlJPuPrk&webtoon_margin=false&workno=BJ01294074

**Comment by hifuclub** [comment]
可能不同的书地址的格式不太一样吧，试着加了点log，好像弹出了网页以后就不动了
![image](https://github.com/cpuopt/DLsite-Play-Downloader/assets/47740858/1009d85c-b270-45c7-8c79-52542d43bce5)
![image](https://github.com/cpuopt/DLsite-Play-Downloader/assets/47740858/a8e43570-ce2b-451c-95ae-fd9372f9ffc2)

**Comment by cpuopt** [comment]
https://github.com/cpuopt/DLsite-Play-Downloader/commit/7a81a39fb6df34345d1a84882f6e9353da411f60
更新到1.2版本就可以了

**Comment by hifuclub** [comment]
目前正常了
