### ISSUE TITLE
無法顯示下載按鈕

### ISSUE THREAD

**Issue by andyching168** [cpuopt/DLsite-Play-Downloader#12]
如圖
![image](https://github.com/user-attachments/assets/706754b7-d807-4ffb-9b94-5c9ef4022c74)
![image](https://github.com/user-attachments/assets/0c1e9efd-ea93-4985-9936-d1ad9b81cb83)

**Comment by cpuopt** [comment]
？PDF可以直接下载的，脚本是用来下载和恢复图片的
