### ISSUE TITLE
处理完成后下载显示404

### ISSUE THREAD

**Issue by ok-y** [cpuopt/DLsite-Play-Downloader#5]
https://www.dlsite.com/comic/work/=/product_id/BJ01363138.html
<img width="1060" alt="截屏2024-04-05 11 36 06" src="https://github.com/cpuopt/DLsite-Play-Downloader/assets/90232106/ec566861-d4f3-48d9-aa75-dabb001d981e">
<img width="548" alt="截屏2024-04-05 11 36 45" src="https://github.com/cpuopt/DLsite-Play-Downloader/assets/90232106/7aad251e-3fb5-415d-a4af-0d1f076452c4">

**Comment by cpuopt** [comment]
![tt](https://github.com/cpuopt/DLsite-Play-Downloader/assets/46257373/61f57cc7-16c0-4862-8ebe-595313ae0b35)
![tt3](https://github.com/cpuopt/DLsite-Play-Downloader/assets/46257373/152bea98-5e6d-442e-84c8-bf6062c99897)
我这边无法复现

**Comment by ok-y** [comment]
> ![tt](https://private-user-images.githubusercontent.com/46257373/320176751-61f57cc7-16c0-4862-8ebe-595313ae0b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzAyOTUsIm5iZiI6MTcxMzI2OTk5NSwicGF0aCI6Ii80NjI1NzM3My8zMjAxNzY3NTEtNjFmNTdjYzctMTZjMC00ODYyLThlYmUtNTk1MzEzYWUwYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEyMTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkM2M3ZDhhOGIyYTVlYzhiNzcxODhlOWFjNDBhMWRlYjJkYjFmNDViMjgxZDZjYTkzYjRiNDM4ZmJkODk1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ifsnN0Gb_FFdy8F8IVDHJOBxraj3oUncCV-Y-DF7Y5c) ![tt3](https://private-user-images.githubusercontent.com/46257373/320176752-152bea98-5e6d-442e-84c8-bf6062c99897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzAyOTUsIm5iZiI6MTcxMzI2OTk5NSwicGF0aCI6Ii80NjI1NzM3My8zMjAxNzY3NTItMTUyYmVhOTgtNWU2ZC00NDJlLTg0YzgtYmY2MDYyYzk5ODk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEyMTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZjgxNDk3OTZlNjA2ZDNlY2QyMzZhYzc4ZDNhYjZmNDE4ODgzMjljYTk3NzJiMDhlMGVkOTkxZDllODQ4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GbY2QV2fTVmGJNwEG60X0mEG3ti1y3_-jgDUawOMetM) 我这边无法复现

搞定了，是fdm下载器拦截导致的问题，关掉扩展用浏览器自带下载即可
