### ISSUE TITLE
下载dlsite play上面的webtoon类型作品时最后一页错位

### ISSUE THREAD

**Issue by zaoe** [cpuopt/DLsite-Play-Downloader#6]
如图
![0123](https://github.com/cpuopt/DLsite-Play-Downloader/assets/18462861/c58dc6cf-ab6d-4cb1-b455-da8ae72302a6)

**Comment by cpuopt** [comment]
只发一张截图没法定位问题

**Comment by zaoe** [comment]
> 只发一张截图没法定位问题

其实不是截图，我是直接把抓到的最后一张发上来了，都需要提供些什么？

**Comment by cpuopt** [comment]
https://github.com/cpuopt/DLsite-Play-Downloader/commit/f0219e8b802f46103c5cf3a57af13547e095803c

已修复 请更新到1.4尝试

**Comment by zaoe** [comment]
> [f0219e8](https://github.com/cpuopt/DLsite-Play-Downloader/commit/f0219e8b802f46103c5cf3a57af13547e095803c)
> 
> 已修复 请更新到1.4尝试

谢谢，经测试已经修复
